/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyLibraryRouteImport } from './routes/my-library'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilesUserIdRouteImport } from './routes/profiles/$userId'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AdminBooksIndexRouteImport } from './routes/admin/books/index'
import { Route as AdminBooksNewRouteImport } from './routes/admin/books/new'
import { Route as AdminBooksEditBookIdRouteImport } from './routes/admin/books/edit.$bookId'

const MyLibraryRoute = MyLibraryRouteImport.update({
  id: '/my-library',
  path: '/my-library',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesUserIdRoute = ProfilesUserIdRouteImport.update({
  id: '/profiles/$userId',
  path: '/profiles/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksIndexRoute = AdminBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksNewRoute = AdminBooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksEditBookIdRoute = AdminBooksEditBookIdRouteImport.update({
  id: '/books/edit/$bookId',
  path: '/books/edit/$bookId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/my-library': typeof MyLibraryRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/profiles/$userId': typeof ProfilesUserIdRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/books': typeof AdminBooksIndexRoute
  '/admin/books/edit/$bookId': typeof AdminBooksEditBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/my-library': typeof MyLibraryRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/profiles/$userId': typeof ProfilesUserIdRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/books': typeof AdminBooksIndexRoute
  '/admin/books/edit/$bookId': typeof AdminBooksEditBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/my-library': typeof MyLibraryRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/profiles/$userId': typeof ProfilesUserIdRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/books/': typeof AdminBooksIndexRoute
  '/admin/books/edit/$bookId': typeof AdminBooksEditBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/my-library'
    | '/auth/signin'
    | '/auth/signup'
    | '/books/$bookId'
    | '/profiles/$userId'
    | '/admin/books/new'
    | '/admin/books'
    | '/admin/books/edit/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/browse'
    | '/my-library'
    | '/auth/signin'
    | '/auth/signup'
    | '/books/$bookId'
    | '/profiles/$userId'
    | '/admin/books/new'
    | '/admin/books'
    | '/admin/books/edit/$bookId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/browse'
    | '/my-library'
    | '/auth/signin'
    | '/auth/signup'
    | '/books/$bookId'
    | '/profiles/$userId'
    | '/admin/books/new'
    | '/admin/books/'
    | '/admin/books/edit/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  MyLibraryRoute: typeof MyLibraryRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  ProfilesUserIdRoute: typeof ProfilesUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-library': {
      id: '/my-library'
      path: '/my-library'
      fullPath: '/my-library'
      preLoaderRoute: typeof MyLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$userId': {
      id: '/profiles/$userId'
      path: '/profiles/$userId'
      fullPath: '/profiles/$userId'
      preLoaderRoute: typeof ProfilesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books/': {
      id: '/admin/books/'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books/new': {
      id: '/admin/books/new'
      path: '/books/new'
      fullPath: '/admin/books/new'
      preLoaderRoute: typeof AdminBooksNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books/edit/$bookId': {
      id: '/admin/books/edit/$bookId'
      path: '/books/edit/$bookId'
      fullPath: '/admin/books/edit/$bookId'
      preLoaderRoute: typeof AdminBooksEditBookIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBooksNewRoute: typeof AdminBooksNewRoute
  AdminBooksIndexRoute: typeof AdminBooksIndexRoute
  AdminBooksEditBookIdRoute: typeof AdminBooksEditBookIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBooksNewRoute: AdminBooksNewRoute,
  AdminBooksIndexRoute: AdminBooksIndexRoute,
  AdminBooksEditBookIdRoute: AdminBooksEditBookIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BrowseRoute: BrowseRoute,
  MyLibraryRoute: MyLibraryRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  ProfilesUserIdRoute: ProfilesUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
